{{ config(
    materialized='view'
) }}

WITH base AS (
    SELECT
        CUSTOMER_ID,
        CUSTOMER_UNIQUE_ID,
        CUSTOMER_ZIP_CODE_PREFIX,
        CUSTOMER_CITY,
        CUSTOMER_STATE
    FROM {{ source('raw', 'OLIST_CUSTOMERS_DATASET') }}
)

SELECT
    NULLIF(TRIM(CUSTOMER_ID), '') AS CUSTOMER_ID,
    NULLIF(TRIM(CUSTOMER_UNIQUE_ID), '') AS CUSTOMER_UNIQUE_ID,
    LPAD(CAST(CUSTOMER_ZIP_CODE_PREFIX AS STRING), 5, '0') AS CUSTOMER_ZIP_CODE_PREFIX,
FROM base